trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Use 'windows-latest' if you're on a Microsoft-hosted agent

variables:
  backendProject: 'SmartFeedbackAPI/SmartFeedbackAPI.csproj'
  nodeVersion: '18.x'
  configuration: 'Release'
  artifactFrontend: 'frontend-dist'
  artifactBackend: 'backend-api'
  publishDir: '$(Build.ArtifactStagingDirectory)'

stages:
  - stage: Build
    displayName: 'Build Backend and Frontend'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:

          # ✅ Checkout repo
          - checkout: self

          # ⚙️ Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
            displayName: 'Install .NET 9 SDK'

          # ⚙️ Restore .NET backend dependencies
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '$(backendProject)'
            displayName: 'Restore Backend Dependencies'

          # 🔨 Build .NET Backend
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '$(backendProject)'
              arguments: '--configuration $(configuration)'
            displayName: 'Build Backend'

          # ⚙️ Install Node.js for Vite build
          - task: NodeTool@0
            inputs:
              versionSpec: '$(nodeVersion)'
            displayName: 'Install Node.js'

          # 🔨 Install & Build Vite Frontend (in repo root)
          - script: |
              npm install
              npm run build
            displayName: 'Build Vite Frontend'

          # ✅ Optional debug log
          - script: |
              echo "Listing frontend dist directory:"
              dir dist
            displayName: 'List Dist Directory (Debug)'

          # 📦 Publish Frontend Artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: '$(artifactFrontend)'
              publishLocation: 'Container'
            displayName: 'Publish Frontend Artifact'

          # 🔨 Publish .NET Backend Output
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              projects: '$(backendProject)'
              arguments: '--configuration $(configuration) --output $(publishDir)'
              zipAfterPublish: true
            displayName: 'Publish Backend Output'

          # 📦 Publish Backend Artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(publishDir)'
              ArtifactName: '$(artifactBackend)'
              publishLocation: 'Container'
            displayName: 'Publish Backend Artifact'
